src/Entity/Student.php
<?php

namespace App\Entity;

use App\Repository\StudentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StudentRepository::class)]
class Student
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\Column(length: 255)]
    private ?string $Sex = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Dateofbirth = null;

    #[ORM\Column]
    private ?int $phone = null;

    #[ORM\ManyToOne]
    private ?Classes $ClassName = null;

    #[ORM\ManyToOne]
    private ?Subject $Subject = null;

   
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getSex(): ?string
    {
        return $this->Sex;
    }

    public function setSex(string $Sex): self
    {
        $this->Sex = $Sex;

        return $this;
    }

    public function getDateofbirth(): ?\DateTimeInterface
    {
        return $this->Dateofbirth;
    }

    public function setDateofbirth(\DateTimeInterface $Dateofbirth): self
    {
        $this->Dateofbirth = $Dateofbirth;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(int $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getClassName(): ?Classes
    {
        return $this->ClassName;
    }

    public function setClassName(?Classes $ClassName): self
    {
        $this->ClassName = $ClassName;

        return $this;
    }

    public function getSubject(): ?Subject
    {
        return $this->Subject;
    }

    public function setSubject(?Subject $Subject): self
    {
        $this->Subject = $Subject;

        return $this;
    }



}

src/Form/StudentType.php
<?php

namespace App\Form;

use App\Entity\Classes;
use App\Entity\Student;
use App\Entity\Subject;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StudentType extends AbstractType{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder 
        ->add('ClassName', EntityType::class,[
            'class' => Classes::class,
            'choice_label' => 'name'
        ])
        ->add('Subject', EntityType::class,[
            'class' => Subject::class,
            'choice_label' => 'name'
        ])
        ->add('Name')
        ->add('Sex')
        ->add('Dateofbirth')
        ->add('Phone')
        ->add('save',SubmitType::class,[
            'label' => "Confirm"
        ]);
    }
    public function configureOptions(OptionsResolver $resolved)
    {
        $resolved->setDefaults([
            'data_class' => Student::class,
        ]);
    }
}

src/Controller/StudentController.php
<?php

namespace App\Controller;

use App\Entity\Student;
use App\Entity\Subject;
use App\Form\StudentType;
use App\Repository\StudentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class StudentController extends AbstractController
{
    private StudentRepository $repo;
    
    public function __construct(StudentRepository $repo)
        {
           $this->repo = $repo;
        }

  

    /**
    * @Route("/listsd", name="list_student")
    */
    public function listStudent(StudentRepository $repo): Response
    {    
         $student = $repo->findAll();
        return $this->render('student/view.html.twig', [
             'Student' => $student
        ]);
    }
    
   /**
    * @Route("/addstudent", name="student_add")
    */
   public function addstudent(Request $req , StudentRepository $repo): Response
   {
    $st = new Student();
        $form = $this->createForm(StudentType::class, $st);
        
        $form->handleRequest($req);
        if($form->isSubmitted()&&$form->isValid()){
          $repo->save($st,true);
          return $this->redirectToRoute('list_student', [], Response::HTTP_SEE_OTHER);
     
        }
       
        return $this->render("student/form.html.twig",[
            'form' => $form->createView(),
    
        ]);
   }

         /**
     * @Route("/editstudent/{id}", name="student_edit",requirements={"id"="\d+"})
     */
    public function editstudent(Request $req, Student $e): Response
    {
           
        $form = $this->createForm(StudentType::class, $e);   
        $form->handleRequest($req);
        if($form->isSubmitted() && $form->isValid()){

            $this->repo->save($e,true);
            return $this->redirectToRoute('list_student', [], Response::HTTP_SEE_OTHER);
        }
        return $this->render("student/form.html.twig",[
            'form' => $form->createView()
        ]);
    }
    /**
    * @Route("/deletestudent/{id}",name="student_delete",requirements={"id"="\d+"})
    */
    
     public function deletestudent(Request $request, Student $st): Response
     {
         $this->repo->remove($st,true);
         return $this->redirectToRoute('list_student', [], Response::HTTP_SEE_OTHER);
     }


}

templates/student/form.html.twig
{% extends "admin.html.twig" %}

{% block title %}
    Admin Page - Product
{% endblock %}
{% block body %}
      <div className="page-heading pb-2 mt-4 mb-2 ">
                <h3>Manager</h3> <a href="{{path('admin')}}"><button type="button" class="btn btn-outline-primary">Back to index</button></a>
            </div>
            <div class="page-content mt-4">
                <div class="card">
                    <div class="card-content">
                        <div class="card-body">
                            {# <form class="form form-vertical" method="POST" action="#"> #}
                            {# {{ form_start(form,{'attr':{'class':'form form-vertical'}} ) }} #}
                                <div class="form-body">
                                    <div class="row">
                                    {{ form_start(form) }}
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label for="first-name-vertical">Class :</label>
                                                {{ form_widget(form.ClassName, {'attr':{'placeholder':'ClassName'}}) }}
                                                {# <input type="text" id="pname" class="form-control"
                                                    name="Product_Name" placeholder="Product Name"
                                                    value =""> #}
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label for="first-name-vertical">Subject :</label>
                                                {{ form_widget(form.Subject, {'attr':{'placeholder':'Subject'}}) }}
                                                {# <input type="text" id="pname" class="form-control"
                                                    name="Product_Name" placeholder="Product Name"
                                                    value =""> #}
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label for="first-name-vertical">Name Student :</label>
                                                {{ form_widget(form.Name, {'attr':{'placeholder':'Name'}}) }}
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label for="contact-info-vertical">Sex :</label>
                                                {{ form_widget(form.Sex, {'attr':{'placeholder':'Sex'}}) }}
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label for="contact-info-vertical">Date of Birth :</label>
                                                {{ form_widget(form.Dateofbirth, {'attr':{'placeholder':'Dateofbirth'}}) }}
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label for="contact-info-vertical">Phone :</label>
                                                {{ form_widget(form.Phone, {'attr':{'placeholder':'Phone'}}) }}
                                            </div>
                                        </div>
                                         
                                        <div class="col-12 d-flex justify-content-end pt-2">
                                        
                                            {{ form_widget(form.save,{'attr':{'class':'btn btn-primary me-2'}}) }}
                                            
                                          <button type="reset"
                                                class="btn btn-secondary">Reset</button>
                                        </div>
                                    </div>
                                </div>
                            {# </form> #}
                            {{ form_end(form) }}
                        </div> <!--card body-->
                    
                    </div> <!--card content-->
                </div> <!--card-->
            </div><!--page content-->
{% endblock %}

templates/student/index.html.twig
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <title>{% block title %}Student Management{% endblock %}</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700 &display=swap" />
  <!-- MDB -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"
    integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <!-- Custom styles -->
  <link rel="stylesheet" type="text/css" href="style.css" />
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-white">
    <!-- Container wrapper -->
    <div class="container">
      <!-- Toggle button -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent1">
        <i class="fas fa-bars"></i>
      </button>

      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent1">
        <!-- Navbar brand -->
        <a class="navbar-brand mt-2 mt-sm-0" href="#">
          <img
            src="https://png.pngtree.com/thumb_back/fw800/background/20210115/pngtree-abstract-gear-mechanism-background-image_528721.jpg"
            height="50" alt="Logo" loading="lazy" />
        </a>
        <!-- Left links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item active">
            <a class="nav-link " href="/">Home</a>
          </li>

        </ul>
        <!-- Left links -->
      </div>
      <!-- Collapsible wrapper -->

      <!-- Right elements -->
      <div class="d-flex align-items-center">

        <!-- Icon -->
        {# <a class="nav-link me-3" href="#">
        <i class="fas fa-shopping-cart"></i> #}
        {# </a>
        <a class="nav-link me-3" href="#">
          <i class="fas fa-sign-in-alt"></i>
        </a> #}
      </div>
      <!-- Right elements -->

    </div>
    <!-- Container wrapper -->
  </nav>
  <!-- Navbar -->
  <link href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <div style="height: 60px"></div>

  {% block body %}
  <!--Main layout-->
  <main>
    <div class="container">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2" style="background-color: #607D8B">
        <!-- Container wrapper -->
        <div class="container-fluid">

          <!-- Navbar brand -->
          <a class="navbar-brand" href="#">Student Management</a>

          <!-- Toggle button -->
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent2">
            <i class="fas fa-bars"></i>
          </button>

          <!-- Collapsible wrapper -->
        </div>
    </div>
    <!-- Container wrapper -->
    </nav>
  </main>
  <!--Main layout-->

  <!--Second layout-->

<div class="container">
 <h1 class="form-title">Student</h1>
<table class="table class-table">
  <thead>
    <tr>
    <th>#</th>
     <th>Class</th>
      <th>Subject</th>
      <th>Name</th>
      <th>Sex</th>
      <th>Phone</th>
      <th>Date Of Birth</th>
    </tr>
  </thead>
  <tbody>
    {% for id in student %}
    <tr>
      <td>{{ id.id }}</td>
      <td >{{id.ClassName}}</td>
      {# <td>{{id.ClassName}}</td>  #}
      <td>{{id.Subject}}</td>
      <td>{{ id.name }}</td>
      <td>{{ id.sex }}</td>
      <td>{{id.phone}}</td>
      <td>{{id.dateofbirth|date("m/d/Y")}}
{% endfor %}
  </tbody>
  </table>

  <ul>
    <li>
    <a href="{{ path('guest') }}"> 
    <button>
    Back to the list
    </button>
    </a>
    </li>
  </ul>
  <style>
    .container {
      max-width: 1500px;
      margin: 0 auto;
    }

    .btn-primary {
      background-color: gray;
      color: white;
      padding: 10px 20px;
      border: none;
      border-radius: 5px;
    }
  </style>
  {% endblock %}
  <!--Second layout-->


  <footer class="text-center text-white mt-4" style="background-color: #607D8B">

    <hr class="text-dark">

    <div class="container">
      <!-- Section: Social media -->
      <section class="mb-3">

        <!-- Facebook -->
        <a class="btn-link btn-floating btn-lg text-white" href="#!" role="button" data-mdb-ripple-color="dark"><i
            class="fab fa-facebook-f"></i></a>

        <!-- Twitter -->
        <a class="btn-link btn-floating btn-lg text-white" href="#!" role="button" data-mdb-ripple-color="dark"><i
            class="fab fa-twitter"></i></a>

        <!-- Google -->
        <a class="btn-link btn-floating btn-lg text-white" href="#!" role="button" data-mdb-ripple-color="dark"><i
            class="fab fa-google"></i></a>

        <!-- Instagram -->
        <a class="btn-link btn-floating btn-lg text-white" href="#!" role="button" data-mdb-ripple-color="dark"><i
            class="fab fa-instagram"></i></a>

        <!-- YouTube -->
        <a class="btn-link btn-floating btn-lg text-white" href="#!" role="button" data-mdb-ripple-color="dark"><i
            class="fab fa-youtube"></i></a>
        <!-- Github -->
        <a class="btn-link btn-floating btn-lg text-white" href="#!" role="button" data-mdb-ripple-color="dark"><i
            class="fab fa-github"></i></a>
      </section>
      <!-- Section: Social media -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2); text-color: #E0E0E0">
      © 2023 Copyright: mdbootstrapz
    </div>
    <!-- Copyright -->
  </footer>
</body>

</html>

templates/student/view.html.twig
{% extends "admin.html.twig" %}

{% block body %}
<a href="{{ path('student_add') }}"> <button type="reset" class="btn btn-primary">Add</button></a>
<div className="page-heading pb-2 mt-4 mb-2 " </div> <table class="table class-table">
  {% for id in Student %}

  <div class="page-content mt-4">

    <tbody>

      <td>

        <div class="card">
          <div class="card-content">

            <div class="card-body">
              <div class="form-body">
                <div class="row">



                  <div class="col-12">
                    <div class="form-group">
                      <label for="first-name-vertical">Classes : {{ id.ClassName }}</label>

                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-group">
                      <label for="contact-info-vertical">Subject : {{ id.Subject }}</label>

                    </div>
                    <div class="col-12">
                    <div class="form-group">
                      <label for="contact-info-vertical">: Name : {{ id.Name }}</label>

                    </div>

                    </div>
                    <div class="col-12">
                    <div class="form-group">
                      <label for="contact-info-vertical">: Sex : {{ id.Sex }}</label>

                    </div>

                    </div>
                    <div class="col-12">
                    <div class="form-group">
                      <label for="contact-info-vertical">: DateofBirth : {{ id.Dateofbirth|date("m/d/Y") }}</label>

                    </div>

                    </div>
                    <div class="col-12">
                    <div class="form-group">
                      <label for="contact-info-vertical">: Phone : {{ id.Phone }}</label>

                    </div>
                        <div class="col-12">
                    <div class="form-group">
                      <a href="{{ path('student_edit',{'id':id.id}) }}" > <button type="reset" class="btn btn-primary">Edit</button></a>
                      <a href="{{ path('student_delete',{'id':id.id}) }}" > <button type="reset" class="btn btn-primary">Delete</button></a>
                  </div> 
                   </div> 
                  </div> </div> <!--card body-->

                  </div>
                  <!--card content-->

                </div>
                <!--card-->

      </td>

    </tbody>

    {% endfor %}
    </table>
  </div>
  <!--page content
{% endblock %}